name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Tests
        run: |
          echo "Running basic tests..."
          test -f index.html || (echo "index.html is missing!" && exit 1)
          test -f index.css || (echo "index.css is missing!" && exit 1)
          test -f index.js || (echo "index.js is missing!" && exit 1)
          echo "All files are present. Tests passed ✅"

      - name: Build Docker Image
        run: |
          docker build -t studentsphere:latest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: |
          docker tag studentsphere:latest paulhanna/studentsphere:latest
          docker push paulhanna/studentsphere:latest
